### PR TITLE
Command Handler and Code Restructuring

### PR DESCRIPTION
**Pull request by AnshumanMahato**
## Changelog

- Implemented a Command Handler.
- Created a template for command files to support the command handler.
- Updated all existing modules to support the command handler.
- tempdata is now stored in the root directory 

## Command Handler
Added a Command Handler function in place of the current if-else based command management structure. This makes command handling dynamic and also allows for better code management. Though the current if-else system is functional, it has some drawbacks:

- As we add more commands, the code becomes more complex and prone to errors.
- We need to update main.js and help.js every time we add a new plugin.

The command handler resolves these issues. It dynamically loads all the command files at runtime from the command folder in a Map. 

```
client.commands = new Map();

fs.readdir("./commands", (err, files) => {
    if (err) 
        return console.error(e);
    files.forEach(commandFile => {
        if(commandFile.endsWith('.js')){
            let commandName = commandFile.replace(".js", "");
            const command = require(`./commands/${commandName}`);
            client.commands.set(commandName,command);
        }
    });
});
```

When the user gives the command message, the handler separates the commands and the arguments. Then it checks for the command and executes it if available. If it's not, then the user is notified.
```
client.on('message_create', async msg => {
    if(msg.fromMe && msg.body.startsWith('!')) {
        let args = msg.body.slice(1).trim().split(/ +/g);
        let command = args.shift().toLowerCase();

        console.log({command,args});

        if (client.commands.has(command)) {
            try {
                await client.commands.get(command).execute(client,msg,args);
            } catch (error) {
                console.log(error);
            }
        }

        else {
            await client.sendMessage(msg.to,'No such command found');
            console.log(client.commands);
        }
    }
});
```

Hence we don't need to update the main.js to add new commands. All we need to do is create a command file and add it to the command folder. We don't need to update the main.js and help.js every time. "main.js" does not require any updating in most cases, and help.js is automatically generated. It makes the system more modular as now commands are separate independent entities. The template for command files is present in the [command_template.js](https://github.com/AnshumanMahato/WhatsBot/blob/main/command_template.js)

## Issues
- I could not adapt the cricket module to the current system because of its dependency on the allcrickettask object as it needs to be accessed by both !cricket and !cricketstop.
- The urban dictionary and weather modules fail to fetch data because of some error on the API side.
- The InfoSpace key is not working. I think it's because my account isn't verified. But that's because InfoSpace always encounters some errors while sending the verification email.

### Note
Previous version of the code is saved in the Legacy Code directory for reference purposes...

### CODE REVIEW

**Comment by cachecleanerjeet** [comment]
Awesome, I will look on it tomorrow. Good job !

**Comment by cachecleanerjeet** [comment]
@AnshumanMahato Delete everything inside legacy code

**Comment by AnshumanMahato** [comment]
@cachecleanerjeet sure. Will do it tomorrow 😊

**Comment by AnshumanMahato** [comment]
@cachecleanerjeet, I removed the Legacy Code directory as was asked by you

> @AnshumanMahato Delete everything inside legacy code (include the folder)

**Comment by cachecleanerjeet** [comment]
@AnshumanMahato Please change the version in `package.json` (1.5.0 > 2.0.0)

**Comment by AnshumanMahato** [comment]
@cachecleanerjeet done

**Comment by AnshumanMahato** [comment]
@cachecleanerjeet 
 - !nopm is now an independent command.
 - dotenv moved to dependency.
 - .env_sample has been added with the default values. An MD file has also been added to explain about .env file.

**Review by cachecleanerjeet — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
