### PR TITLE
Added new Command 🥳

### PR DESCRIPTION
**Pull request by TOXIC-DEVIL**
TTS - Convert text to sound
@cachecleanerjeet

### CODE REVIEW

**Comment by TOXIC-DEVIL** [comment]
> It will not work because it needed to be called by main.js

So?

**Comment by TOXIC-DEVIL** [comment]
Yes, removed label, this means you are going to maintain 🥳💖

**Comment by cachecleanerjeet** [comment]
I can but what's the point of merging this pull request then?

**Comment by TOXIC-DEVIL** [comment]
> I can but what's the point of merging this pull request then?

Yes, because You got an idea about a command also, I contributed, so there is an option in github to allow edit of maintainers, this feature in github is to edit some mistakes and merge it

**Comment by TOXIC-DEVIL** [comment]
Please feel free to maintain it 💖

**Comment by TOXIC-DEVIL** [comment]
Or I will call it now wait

**Comment by TOXIC-DEVIL** [comment]
Please feel free to maintain it 💖 @cachecleanerjeet

**Comment by TOXIC-DEVIL** [comment]
😑 my 1 hrs wasted for you! I just pulled by Sympathy to this bot, because you are only the developer, I was going to use. But nope I will never! Also the most famous modular WhatsApp is Asena, [WhatsAsena](https://github.com/Phaticusthiccy/WhatsAsenaDuplicated) with 160K Users 😒😼

**Pull request closed without merging**
